@startuml

hide empty members

skinparam {
    DefaultFontName "Linux Biolinum O"
    DefaultFontSize 9
    Style strictuml
    Monochrome true
    LineType ortho
    RankSep 40
    ClassBorderThickness 0.7
}

entity Customer
entity Staff
entity Supplier
entity Sale_Head
entity Sale_Line
entity Order_Head
entity Order_Line
entity Product
entity Assembly
entity Component

Customer ||..o{ Sale_Head
Supplier -[hidden]- Order_Head
Supplier ||..o{ Order_Head
Sale_Head }o.|| Staff
Staff ||.o{ Order_Head
Sale_Head ||--|{ Sale_Line
Order_Head ||--|{ Order_Line
Sale_Line }o--|| Product
Supplier ||..o{ Component
Order_Line }o--|| Component
Product ||-|{ Assembly
Assembly }|-|| Component

@enduml
